[2021-09-16 14:54:34] INFO:django.utils.autoreload: Watching for file changes with StatReloader autoreload.py:598
[2021-09-16 14:58:16] INFO:django.utils.autoreload: /data/devops/svn/urls.py changed, reloading. autoreload.py:222
[2021-09-16 14:58:18] INFO:django.utils.autoreload: Watching for file changes with StatReloader autoreload.py:598
[2021-09-16 14:59:00] INFO:django.utils.autoreload: Watching for file changes with StatReloader autoreload.py:598
[2021-09-16 15:00:37] INFO:django.utils.autoreload: Watching for file changes with StatReloader autoreload.py:598
[2021-09-16 15:03:21] INFO:django: svn操作失败，已经发布的系统不能再次封版。 views.py:168
[2021-09-16 15:05:23] INFO:django: 解板请求: bash   /data/script/branchRw.sh http://svn.cnzhonglunnet.com/svn/zlnet/code/project/branch/2021/09/20210915/apiv5 views.py:185
[2021-09-16 15:05:24] INFO:django: svn分支: http://svn.cnzhonglunnet.com/svn/zlnet/code/project/branch/2021/09/20210915/apiv5  解版成功 views.py:194
[2021-09-16 15:07:00] INFO:django: 分支调整: bash /data/script/branchNew.sh 2021 09 16 zlscms Java 分支操作备注:修复线上分销员异常问题 views.py:289
[2021-09-16 15:07:12] INFO:django: svn分支: http://svn.cnzhonglunnet.com/svn/zlnet/code/project/branch/2021/09/20210916/zlscms 创建成功 views.py:295
[2021-09-16 15:12:08] INFO:django.utils.autoreload: /data/devops/svn/views.py changed, reloading. autoreload.py:222
[2021-09-16 15:12:10] INFO:django.utils.autoreload: Watching for file changes with StatReloader autoreload.py:598
[2021-09-16 15:13:03] INFO:django: 封板请求: bash  /data/script/branchRo.sh http://svn.cnzhonglunnet.com/svn/zlnet/code/project/branch/2021/09/20210915/apiv5 views.py:157
[2021-09-16 15:13:04] INFO:django: svn分支:  http://svn.cnzhonglunnet.com/svn/zlnet/code/project/branch/2021/09/20210915/apiv5 封版成功 views.py:165
[2021-09-16 15:14:49] INFO:django: 解板请求: bash   /data/script/branchRw.sh http://svn.cnzhonglunnet.com/svn/zlnet/code/project/branch/2021/09/20210915/apiv5 views.py:189
[2021-09-16 15:14:50] INFO:django: svn分支: http://svn.cnzhonglunnet.com/svn/zlnet/code/project/branch/2021/09/20210915/apiv5  解版成功 views.py:198
[2021-09-16 15:24:10] INFO:django.utils.autoreload: /data/devops/svn/views.py changed, reloading. autoreload.py:222
[2021-09-16 15:24:13] INFO:django.utils.autoreload: Watching for file changes with StatReloader autoreload.py:598
[2021-09-16 15:32:22] INFO:django.utils.autoreload: /data/devops/svn/views.py changed, reloading. autoreload.py:222
[2021-09-16 15:32:24] INFO:django.utils.autoreload: Watching for file changes with StatReloader autoreload.py:598
[2021-09-16 15:32:49] INFO:django.utils.autoreload: /data/devops/svn/urls.py changed, reloading. autoreload.py:222
[2021-09-16 15:32:51] INFO:django.utils.autoreload: Watching for file changes with StatReloader autoreload.py:598
[2021-09-16 15:33:28] INFO:django: 解板请求: bash   /data/script/branchRw.sh http://svn.cnzhonglunnet.com/svn/zlnet/code/project/branch/2021/09/20210915/apiv5 views.py:193
[2021-09-16 15:33:29] INFO:django: svn分支: http://svn.cnzhonglunnet.com/svn/zlnet/code/project/branch/2021/09/20210915/apiv5  解版成功 views.py:202
[2021-09-16 15:34:10] INFO:django: 封板请求: bash  /data/script/branchRo.sh http://svn.cnzhonglunnet.com/svn/zlnet/code/project/branch/2021/09/20210915/apiv5 views.py:161
[2021-09-16 15:34:11] INFO:django: svn分支:  http://svn.cnzhonglunnet.com/svn/zlnet/code/project/branch/2021/09/20210915/apiv5 封版成功 views.py:169
[2021-09-16 15:34:27] ERROR:django.request: Internal Server Error: /svn/jenkinsAutoAuth/ log.py:228
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/data/devops/svn/views.py", line 44, in jenkinsAutoAuth
    utcPublishTime = datetime.utcfromtimestamp(
AttributeError: module 'datetime' has no attribute 'utcfromtimestamp'
[2021-09-16 15:35:16] INFO:django.utils.autoreload: /data/devops/svn/views.py changed, reloading. autoreload.py:222
[2021-09-16 15:35:18] INFO:django.utils.autoreload: Watching for file changes with StatReloader autoreload.py:598
